name: Deploy

on:
  workflow_call:
    inputs:
      repository:
        required: true
        type: string
    secrets:
      server_host:
        required: true
      server_key:
        required: true
jobs:
  testConnection:
    runs-on: ubuntu-latest

    steps:
      - name: Test connection to online machine with SSH
        uses: JimCronqvist/action-ssh@0.1.1
        with:
          hosts: ${{ secrets.server_host }}
          privateKey: ${{ secrets.server_key }}

  main:
    runs-on: ubuntu-latest

    steps:
      - name: Connect to online machine with SSH
        uses: JimCronqvist/action-ssh@0.1.1
        with:
          hosts: ${{ secrets.server_host }}
          privateKey: ${{ secrets.server_key }}

      - name: Update the online machine with SSH
        uses: JimCronqvist/action-ssh@0.1.1
        with:
          command: |
            cd ${{ inputs.repository }}/
            git pull 
            npm install --save --legacy-peer-deps
            sudo pm2 restart all
          hosts: ${{ secrets.server_host }}
          privateKey: ${{ secrets.server_key }}
